apiVersion: v2
name: local-path-exporter
description: A Prometheus exporter for local-path PVC storage usage
type: application
version: 0.1.0
appVersion: "1.0.0"

home: https://github.com/tmusial99/local-path-exporter
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
sources:
  - https://github.com/tmusial99/local-path-exporter
maintainers:
  - name: tmusial99
    email: tmusial99@gmail.com
annotations:
  artifacthub.io/readme: https://raw.githubusercontent.com/tmusial99/local-path-exporter/master/README.md
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/tmusial99/local-path-exporter
  artifacthub.io/images: |
    - name: local-path-exporter
      image: ghcr.io/tmusial99/local-path-exporter:1.0.0
