{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "local-path-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "local-path-exporter.labels" . | nindent 4 }}
      {{- with .Values.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "local-path-exporter.selectorLabels" . | nindent 6 }}

  {{- if .Values.serviceMonitor.matchNamespace }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- else }}
  namespaceSelector:
    any: true
  {{- end }}

  endpoints:
    - port: {{ .Values.service.name }}
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  {{- end }}